# Generated by Django 6.0.4 on 2026-04-28 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_name', models.CharField(choices=[('api_calls', 'API Calls'), ('team_members', 'Team Members'), ('reports_generated', 'Reports Generated'), ('storage_usage', 'Storage Usage'), ('emails_sent', 'Emails Sent')], max_length=100)),
                ('used_units', models.PositiveIntegerField(default=0)),
                ('usage_limit', models.PositiveIntegerField(default=1000)),
                ('is_over_limit', models.BooleanField(default=False)),
                ('billing_month', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='organizations.organization')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='subscriptions.subscriptionplan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
